namespace TradeCapture.Api.Soap.Contracts;

/// <summary>
/// CLIENT-side SOAP contract, annotated with <c>System.ServiceModel</c> attributes, used by the
/// WCF <c>ChannelFactory</c>. Structurally identical to the server contract
/// (<see cref="ICurrencyRateSoapContract"/>); they interoperate because Name, Namespace and SOAP
/// Action match exactly. (In a real "consume an external WSDL" scenario this interface would
/// instead be generated by <c>dotnet-svcutil</c>.)
/// </summary>
[System.ServiceModel.ServiceContract(Name = CurrencyRateContract.ServiceName, Namespace = CurrencyRateContract.Namespace)]
public interface ICurrencyRateSoapClient
{
    [System.ServiceModel.OperationContract(
        Action = CurrencyRateContract.GetRateAction,
        ReplyAction = CurrencyRateContract.GetRateReplyAction)]
    CurrencyRateDto? GetRate(string fromCurrency, string toCurrency, DateTime asOf);
}
